#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
PROG="/usr/bin/minecraft_exporter"
OPTIONS="--web.listen-address=:9940"

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" "${OPTIONS}"
	procd_close_instance
}
